name: ChatBotCI/CD

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]


env:
  DOTNET_VERSION: '10.0.x'
  SOLUTION_FILE: ChatBotApplication2.slnx
  PROJECT_FILE: ChatBotApplication2/ChatBotApplication2.csproj

jobs:

  build:

    name: Build

    runs-on: windows-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Packages
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build Solution
        run: |
          dotnet build ${{ env.SOLUTION_FILE }} `
            --configuration Release `
            --no-restore

  test:

    name: Test

    needs: build

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Run Unit Tests
        run: |
          dotnet test ${{ env.SOLUTION_FILE }} `
            --configuration Release `
            --no-build `
            --verbosity normal

  publish:

    name: Publish

    needs: test

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Create Publish Profile
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "./PublishProfile" | Out-Null
           @'${{ secrets.PUBLISH_PROFILE }}'@ | Set-Content "./PublishProfile/Monster.pubxml"

      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish

  deploy:
    name: Deploy to MonsterASP.NET
    needs: publish
    if: github.ref == 'refs/heads/master'
    runs-on: windows-latest
    steps:
     - name: Download published files
       uses: actions/download-artifact@v4
       with:
        name: published-app
        path: publish

     - name: Deploy to MonsterASP.NET
       shell: pwsh
       run: |
        msbuild "${{ env.PROJECT_FILE }}" `
        /p:DeployOnBuild=true `
        /p:PublishProfile="./PublishProfile/Monster.pubxml" `
        /p:Configuration=Release
